### ISSUE TITLE
Move a body with  local coordinates 

### ISSUE THREAD

**Issue by anemol** [saharan/OimoPhysics#10]
If I apply a force with applyImpulse or linearVelocity to x on an object, it moves relative to the global coordinates. I would like it to move relative to its local coordinates (so depending on its rotation).

How to do?

**Comment by saharan** [comment]
You can use `RigidBody.getWorldVector` to transform a vector from local space to global space. To apply an unit linear force along the x axis of a rigid body `r`, the following code can be used:
```hx
var localForce = new Vec3(1, 0, 0);
var globalForce = r.getWorldVector(localForce);
r.applyForceToCenter(globalForce);
```
hope it helps :)

**Comment by anemol** [comment]
Thanks for help. :)
Unfortunately, i use oimo for nodejs (https://github.com/lo-th/Oimo.js/) and these functions aren't available. I thought i could use the same functions, but the project must be obsolete.
I will check if it is possible to export haxe for nodejs module.
