### ISSUE TITLE
Cannot use as haxe library?

### ISSUE THREAD

**Issue by Smoozilla** [saharan/OimoPhysics#12]
I would like to use this library to compile to native android via lime, yet I've found the code is riddled with build macros to turn it into a JavaScript file.

Can I use this library directly in a Haxe project? Thanks.

**Comment by saharan** [comment]
You can use OimoPhysics for all platforms, directly. These macros help compile it into a JS file, but never prevent from compiling it into other formats than JS. Otherwise it's a bug so I'd try to fix it.
Thanks,

**Comment by Smoozilla** [comment]
Again thank you for everything, this rendition of OIMO is by far my favorite physics engine available in JavaScript.

I am running it on the node side, and sticking to pure NodeJS for the project, transpiling for the client. I've done a few edits on the offered binary and it works fine, though not as elegant as if it were a node module I could npm install. TypeScript would be nice but personally at this point I'm far enough into the JavaScript I'd like to revoke my TS vote. :grin:
