### ISSUE TITLE
How to rotate a rigid body around a point or any axis, and around three-quarters of the body, rather than around the center

### ISSUE THREAD

**Issue by wenrenqiang** [saharan/OimoPhysics#13]
How to rotate a rigid body around a point or any axis, and around three-quarters of the body, rather than around the center

**Comment by saharan** [comment]
You can use [Mat3#appendRotation](https://saharan.github.io/OimoPhysics/oimo/common/Mat3.html#appendRotation) to make a rotation matrix around an arbitrary axis.
There's no method to directly rotate a rigid body around a specified point, so you should apply some translation after the rotation to get desired effect. [RigidBody#getWorldPoint](https://saharan.github.io/OimoPhysics/oimo/dynamics/rigidbody/RigidBody.html#getWorldPoint) and [RigidBody#translate](https://saharan.github.io/OimoPhysics/oimo/dynamics/rigidbody/RigidBody.html#translate) may help you to do that.

**Comment by saharan** [comment]
Yes, revolute joints play the same role as hinge joints (as written in README.md). There are no parent-child relationships between rigid bodies, though.
