### ISSUE TITLE
[Q] Is this project abandoned?

### ISSUE THREAD

**Issue by trsh** [saharan/OimoPhysics#24]

**Comment by OleksiiMaksymovVBT** [comment]
@trsh I hope not, because we are starting to use it

**Comment by trsh** [comment]
@OleksiiMaksymovVBT hehe. There are 2 options: 1) abandoned, 2) It has reached it's purpose and doesn't need any quick updates. I guess it a mix of 1 and 2 :/

**Comment by OleksiiMaksymovVBT** [comment]
@trsh btw we are on the finish line with adding here typescript declarations and having bundle as ES Modules.

**Comment by OleksiiMaksymovVBT** [comment]
@saharan will you be able to check our pull requests?

**Comment by trsh** [comment]
@OleksiiMaksymovVBT I only care about haxe :)))

**Comment by OleksiiMaksymovVBT** [comment]
@trsh lol :D

**Comment by saharan** [comment]
I haven't committed to this project for years because of personal reasons, it's not abandoned. Recently I switched my development environment from HaxeDevelop to Visual Studio Code, and I'm planning to add some related files, along with the minor fixes to adapt to the latest Haxe.
