### ISSUE TITLE
DebugDraw - How?

### ISSUE THREAD

**Issue by Snky** [saharan/OimoPhysics#35]
How do we render the DebugDraw in Haxe?
I've created the debug draw, set the world debug draw to this.
Now how do we actually display it?
Currently using: OpenFL->Away3D->Oimo

**Comment by saharan** [comment]
You can call [`World.debugDraw`](https://saharan.github.io/OimoPhysics/oimo/dynamics/World.html#debugDraw) after setting customized `DebugDraw` instance (you should create a class that extends `DebugDraw`). You don't have to implement (by overriding) all methods in the interface, but at least three of them (`point`, `triangle`, `line`) should be implemented.

**Comment by Snky** [comment]
Dear Saharan, I successfully drew triangles for, triangles and quads I believe.
I'm having an issue with ConeGeometry, I do not think it is displaying/working properly for me.
Please see below debug images, any idea?

![aa](https://user-images.githubusercontent.com/7985031/147297283-931532df-4a73-4436-a81c-586fe444fb8d.PNG)
![bb](https://user-images.githubusercontent.com/7985031/147297284-453a8a70-0e3e-44cb-919c-669e20148f84.PNG)
