### ISSUE TITLE
RigidBody awake condition little error

### ISSUE THREAD

**Issue by tor4kichi** [saharan/OimoPhysics#4]
こんにちわsaharanさん、はじめまして。OimoPhysics.haxeとしてOimoPhysicsをforkしたtor4kichiと言います。よろしくお願いします。
RigidBodyのスリープ解除条件の記述についてです。

https://github.com/saharan/OimoPhysics/blob/master/src/com/element/oimo/physics/dynamics/World.as

_問題の箇所_
World.as / function step / line 384~385

```
var lv:Vec3 = tmpB.linearVelocity;
var av:Vec3 = tmpB.linearVelocity;
```

とありますが、これは

```
var lv:Vec3 = tmpB.linearVelocity;
var av:Vec3 = tmpB.angularVelocity;
```

と書こうとされていたのではないでしょうか？

**Comment by saharan** [comment]
tor4kichiさん
ご報告ありがとうございます。2年越しになってしまいすみません。

ご指摘の通り、確かに書き間違えていたので修正いたしました。ありがとうございます。
