### ISSUE TITLE
error in GenericJoint

### ISSUE THREAD

**Issue by lo-th** [saharan/OimoPhysics#40]
i see error in getRotationalSpringDampers of GenericJoint

return _translSds.toArray();
should be 
return _rotSds.toArray();

**Comment by lo-th** [comment]
is there any joint iterations setting ? can be usefull  for strong joint

**Comment by Dev-MarkoF** [comment]
On that note: Is there a setting for welding a joint? There is often a need of just connecting two bodies without any degrees of freedom, similar to a classic parent/child relationship in a hierarchy.

**Comment by lo-th** [comment]
you can use Generic joint 
by default limite is 0,0 on each axe and rotation

**Comment by saharan** [comment]
Thanks for reporting, this is gonna be fixed soon.

> is there any joint iterations setting ? can be usefull for strong joint

I believe setting `JointConfig.solverType` to `ConstraintSolverType.DIRECT` will be a lot helpful to make a specific joint stiffer.

**Comment by saharan** [comment]
fixed in `1.2.2`!
