### ISSUE TITLE
Please, upload a new version to NPM

### ISSUE THREAD

**Issue by 8Observer8** [saharan/OimoPhysics#53]
Hi, @saharan. Please, upload a new version (v1.2.3) to NPM. The latest version of OimoPysics (v1.2.3) was released on January 29, 2022, but it was not uploaded to NPM. v1.2.2 was published 3 years ago.

**Comment by saharan** [comment]
Okay, but it's @OleksiiMaksymovVBT who currently has the ownership of the package.

Hi @OleksiiMaksymovVBT, thank you for setting up the package at that time! Can you please transfer the ownership of the package to me? My account is https://www.npmjs.com/~saharan.

**Comment by 8Observer8** [comment]
The latest version of the engine can be installed with this command: `npm i saharan/OimoPhysics`. I think this version is not stable for production. But I have no other choice.

**Comment by 8Observer8** [comment]
A specific stable version of OimoPhysics can be installed using this command:

> npm i saharan/OimoPhysics#v1.2.4

**Comment by fy0** [comment]
> A specific stable version of OimoPhysics can be installed using this command:
> 
> > npm i saharan/OimoPhysics#v1.2.4

I suggest adding this to the README.

**Comment by 8Observer8** [comment]
I had this problems on the server side ["Hello World" on the server side with OimoPhysics](https://github.com/saharan/OimoPhysics/issues/57) but it was solved by installing v1.2.3:

```
npm i saharan/OimoPhysics#v1.2.3
```

**Comment by pschroen** [comment]
@saharan if I could make a recommendation, what if instead you moved the package to a [scoped package](https://docs.npmjs.com/creating-and-publishing-an-organization-scoped-package), something like `@oimo/oimophysics` if that works?

**Comment by saharan** [comment]
That sounds nice, I'll give it a try later!

**Comment by saharan** [comment]
Hey @mrEuler (formerly @OleksiiMaksymovVBT), are you still alive on GitHub?
Please transfer the ownership of the package, otherwise I have to make a scoped package to update the lib on NPM.

**Comment by 8Observer8** [comment]
@saharan I cannot install 1.2.5:

> npm i saharan/OimoPhysics#v1.2.5

```
npm ERR! code 1
npm ERR! Command failed: git checkout v1.2.5
npm ERR! error: pathspec 'v1.2.5' did not match any file(s) known to git
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\8Observer8\AppData\Roaming\npm-cache\_logs\2024-06-01T12_34_40_384Z-debug.log
```

**Comment by pschroen** [comment]
@8Observer8 the `#v1.2.5` part is referencing a tag which doesn't exist.

For now you can simply install from the master branch:
```
npm i saharan/OimoPhysics
```

**Comment by saharan** [comment]
Sorry for the version mismatch! I'll fix that in a few days.

**Comment by saharan** [comment]
We will discuss how we do the npm package in #75!
