### ISSUE TITLE
ConvexHullGeometry.hx - _volume (issue)

### ISSUE THREAD

**Issue by Snky** [saharan/OimoPhysics#62]
I believe I am correctly generating collision meshes through ConvexHullGeometry.hx - but sometimes the _volume is zero at line 67:

_volume = sizex * sizey * sizez;

Any idea what's going on here? The object is dynamic but it's not moving, the debug display, all the lines are grey (not blue/red/green/yellow). So for now I've changed the above to:

if ((sizex * sizey * sizez) != 0)
        _volume = sizex * sizey * sizez;

**Comment by saharan** [comment]
Input of ConvexHullGeometry must not be degenerated (i.e. there must not be a plane that contains all the vertices on it), but setting a minimum volume to avoid unintended behavior might be a good idea.
