### ISSUE TITLE
Support for Compiling to SWC

### ISSUE THREAD

**Issue by Fancy2209** [saharan/OimoPhysics#70]
Since this Supports JS and TS, why not AS3?

**Comment by saharan** [comment]
Although it looks like Haxe still supports SWF as a compile target, I doubt any new project will use this library from AS3. Also I'm not sure if Haxe can output SWF as a library and I cannot maintain it since I'm not using AS3 anymore...

**Comment by Fancy2209** [comment]
I've added this in my fork, it compiles but I haven't tested it yet.
Since you can't maintain it I won't PR it
https://github.com/Fancy2209/OimoPhysics

**Comment by Fancy2209** [comment]
It does work!
![imagem](https://github.com/saharan/OimoPhysics/assets/64917206/8715a254-13ee-4696-b111-c9e6c8ef19de)
https://github.com/saharan/OimoPhysics/assets/64917206/38b09bf2-c064-4523-841c-a48d5e11d9da
