### ISSUE TITLE
Please, create the Discussions tab

### ISSUE THREAD

**Issue by 8Observer8** [saharan/OimoPhysics#71]
Please, create the Discussions tab here:

![image](https://github.com/saharan/OimoPhysics/assets/3908473/986a2b1c-4395-4a7b-ace8-44e7deebdf17)

**Comment by saharan** [comment]
I opened it!

**Comment by ivan-enzhaev** [comment]
Example of third person movement and debug drawer using OimoPhysics and Three.js: https://github.com/saharan/OimoPhysics/discussions/74
