### ISSUE TITLE
Add Linear Factor

### ISSUE THREAD

**Issue by moisesjpelaez** [saharan/OimoPhysics#73]
The objects already have a rotation factor and inertia. It would be nice to have linear factors as well in `_applyTranslation` from `oimo.dynamics.rigidbody.RigidBody`.

**Comment by saharan** [comment]
Unfortunately mass is a scalar and not a matrix like inertia moment and handling anisotropicity directly in `RigidBody` is difficult (for isotropic linear factor you can just change mass).
If you want to limit linear movements for some axes, you can utilize `GenericJoint` by setting its `TranslationalLimitMotor`.

e.g. to lock the X-axis of a generic joint you can `genericJoint.getTranslationalLimitMotors()[0].setLimits(0, 0)`.
